In [2]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns 
import warnings
warnings.filterwarnings('ignore')

In [3]:
df=pd.read_csv('train.txt',sep=';',names=['text','emotion'])

In [4]:
df.head()

                                                text  emotion
0                            i didnt feel humiliated  sadness
1  i can go from feeling so hopeless to so damned...  sadness
2   im grabbing a minute to post i feel greedy wrong    anger
3  i am ever feeling nostalgic about the fireplac...     love
4                               i am feeling grouchy    anger

In [5]:
df.isnull().sum()

text       0
emotion    0
dtype: int64

convert emotions into numbers

In [6]:
unique_emotions = df['emotion'].unique()

In [7]:
emotion_num={}
i=0
for emotion in unique_emotions:
    emotion_num[emotion]=i
    i+=1

In [8]:
df['emotion_num'] = df['emotion'].map(emotion_num)

In [9]:
df

                                                    text  emotion  emotion_num
0                                i didnt feel humiliated  sadness            0
1      i can go from feeling so hopeless to so damned...  sadness            0
2       im grabbing a minute to post i feel greedy wrong    anger            1
3      i am ever feeling nostalgic about the fireplac...     love            2
4                                   i am feeling grouchy    anger            1
...                                                  ...      ...          ...
15995  i just had a very brief time in the beanbag an...  sadness            0
15996  i am now turning and i feel pathetic that i am...  sadness            0
15997                     i feel strong and good overall      joy            5
15998  i feel like this was such a rude comment and i...    anger            1
15999  i know a lot but i feel so stupid because i ca...  sadness            0

[16000 rows x 3 columns]

Removing punctuations

In [10]:
import string

In [11]:
def remove_punctuation(text):
    return text.translate(str.maketrans('', '', string.punctuation))
df['text'] = df['text'].apply(remove_punctuation)

In [12]:
# Removing numbers from the text
def remove_numbers(text):
    new=""
    for i in text:
        if not i.isdigit():
            new=new+i
    return new
df['text'] = df['text'].apply(remove_numbers)

In [13]:
# REMOVE imojis
def remove_imojis(text):
    new=""
    for i in text:
        if i.isascii():
            new=new+i
    return new
df['text'] = df['text'].apply(remove_imojis)

# now we will remove stop words from the text. Stop words are the most common words in a language, such as "the", "is", "in", etc. These words do not carry much meaning and can be removed from the text to improve the performance of the model.

Tokenization

In [14]:
%pip install nltk

Requirement already satisfied: nltk in c:\Users\asadk\AppData\Local\Programs\Python\Python313\Lib\site-packages (3.10.3)
Requirement already satisfied: defusedxml in c:\Users\asadk\AppData\Local\Programs\Python\Python313\Lib\site-packages (from nltk) (0.7.1)
Requirement already satisfied: click in c:\Users\asadk\AppData\Local\Programs\Python\Python313\Lib\site-packages (from nltk) (8.5.0)
Requirement already satisfied: joblib in c:\Users\asadk\AppData\Local\Programs\Python\Python313\Lib\site-packages (from nltk) (1.6.0)
Requirement already satisfied: regex>=2021.8.3 in c:\Users\asadk\AppData\Local\Programs\Python\Python313\Lib\site-packages (from nltk) (2026.9.10)
Requirement already satisfied: tqdm in c:\Users\asadk\AppData\Local\Programs\Python\Python313\Lib\site-packages (from nltk) (4.70.1)
Requirement already satisfied: cloudpickle>=3.0 in c:\Users\asadk\AppData\Local\Programs\Python\Python313\Lib\site-packages (from joblib->nltk) (3.1.2)
Requirement already satisfied: colorama in c:\Users\asadk\AppData\Local\Programs\Python\Python313\Lib\site-packages (from tqdm->nltk) (0.4.6)
Note: you may need to restart the kernel to use updated packages.

In [15]:
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

In [16]:
nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\asadk\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\asadk\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\asadk\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [17]:
stop_words = set(stopwords.words('english'))
len(stop_words)

198

In [18]:
# now check the text column and remove the stop words from the text column
def remove(txt):
    word_tokens = word_tokenize(txt)
    cleaned=[]
    for i in word_tokens:
        if i not in stop_words:
            cleaned.append(i)
    return ' '.join(cleaned)

In [19]:
df['text'] = df['text'].apply(remove)

In [20]:
df.loc[2]['text']

'im grabbing minute post feel greedy wrong'

In [21]:
# bag of words model
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer()

documents=["I love pizza","pizza is good", "I love pasta", "pasta is good"]

x=vectorizer.fit_transform(documents)
print("Vocabulary:\n",vectorizer.get_feature_names_out())
print("Bag of words representation:\n",x.toarray())

Vocabulary:
 ['good' 'is' 'love' 'pasta' 'pizza']
Bag of words representation:
 [[0 0 1 0 1]
 [1 1 0 0 1]
 [0 0 1 1 0]
 [1 1 0 1 0]]

In [23]:
y=vectorizer.fit_transform(df['text'])
print("Vocabulary for the dataset:\n",vectorizer.get_feature_names_out())
print("Bag of words representation for the dataset:\n",y.toarray())

Vocabulary for the dataset:
 ['aa' 'aaaaaaand' 'aaaaand' ... 'zum' 'zumba' 'zz']
Bag of words representation for the dataset:
 [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]