In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
import warnings
warnings.filterwarnings('ignore')

In [24]:
from sklearn.preprocessing import LabelEncoder, StandardScaler, MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
from sklearn.linear_model import Perceptron
from sklearn.datasets import load_digits

from tensorflow import keras
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Conv2D
from tensorflow.keras.layers import MaxPooling2D
from tensorflow.keras.models import Sequential
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.layers import Dropout

In [25]:
df=load_digits()
# df.head(5)

In [26]:
df=pd.DataFrame(data=df.data, columns=df.feature_names)
df['target']=load_digits().target

In [27]:
df.head()

,pixel_0_0,pixel_0_1,pixel_0_2,pixel_0_3,pixel_0_4,pixel_0_5,pixel_0_6,pixel_0_7,pixel_1_0,pixel_1_1,...,pixel_6_7,pixel_7_0,pixel_7_1,pixel_7_2,pixel_7_3,pixel_7_4,pixel_7_5,pixel_7_6,pixel_7_7,target
0,0.0,0.0,5.0,13.0,9.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,6.0,13.0,10.0,0.0,0.0,0.0,0
1,0.0,0.0,0.0,12.0,13.0,5.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,11.0,16.0,10.0,0.0,0.0,1
2,0.0,0.0,0.0,4.0,15.0,12.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,3.0,11.0,16.0,9.0,0.0,2
3,0.0,0.0,7.0,15.0,13.0,1.0,0.0,0.0,0.0,8.0,...,0.0,0.0,0.0,7.0,13.0,13.0,9.0,0.0,0.0,3
4,0.0,0.0,0.0,1.0,11.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,2.0,16.0,4.0,0.0,0.0,4

In [28]:
X=df.drop('target', axis=1)
y=df['target']

In [29]:
X.isnull().sum()

pixel_0_0    0
pixel_0_1    0
pixel_0_2    0
pixel_0_3    0
pixel_0_4    0
            ..
pixel_7_3    0
pixel_7_4    0
pixel_7_5    0
pixel_7_6    0
pixel_7_7    0
Length: 64, dtype: int64

In [30]:
X.info()

<class 'pandas.DataFrame'>
RangeIndex: 1797 entries, 0 to 1796
Data columns (total 64 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   pixel_0_0  1797 non-null   float64
 1   pixel_0_1  1797 non-null   float64
 2   pixel_0_2  1797 non-null   float64
 3   pixel_0_3  1797 non-null   float64
 4   pixel_0_4  1797 non-null   float64
 5   pixel_0_5  1797 non-null   float64
 6   pixel_0_6  1797 non-null   float64
 7   pixel_0_7  1797 non-null   float64
 8   pixel_1_0  1797 non-null   float64
 9   pixel_1_1  1797 non-null   float64
 10  pixel_1_2  1797 non-null   float64
 11  pixel_1_3  1797 non-null   float64
 12  pixel_1_4  1797 non-null   float64
 13  pixel_1_5  1797 non-null   float64
 14  pixel_1_6  1797 non-null   float64
 15  pixel_1_7  1797 non-null   float64
 16  pixel_2_0  1797 non-null   float64
 17  pixel_2_1  1797 non-null   float64
 18  pixel_2_2  1797 non-null   float64
 19  pixel_2_3  1797 non-null   float64
 20  pixel_2_4  1797 non-null   float64
 21  pixel_2_5  1797 non-null   float64
 22  pixel_2_6  1797 non-null   float64
 23  pixel_2_7  1797 non-null   float64
 24  pixel_3_0  1797 non-null   float64
 25  pixel_3_1  1797 non-null   float64
 26  pixel_3_2  1797 non-null   float64
 27  pixel_3_3  1797 non-null   float64
 28  pixel_3_4  1797 non-null   float64
 29  pixel_3_5  1797 non-null   float64
 30  pixel_3_6  1797 non-null   float64
 31  pixel_3_7  1797 non-null   float64
 32  pixel_4_0  1797 non-null   float64
 33  pixel_4_1  1797 non-null   float64
 34  pixel_4_2  1797 non-null   float64
 35  pixel_4_3  1797 non-null   float64
 36  pixel_4_4  1797 non-null   float64
 37  pixel_4_5  1797 non-null   float64
 38  pixel_4_6  1797 non-null   float64
 39  pixel_4_7  1797 non-null   float64
 40  pixel_5_0  1797 non-null   float64
 41  pixel_5_1  1797 non-null   float64
 42  pixel_5_2  1797 non-null   float64
 43  pixel_5_3  1797 non-null   float64
 44  pixel_5_4  1797 non-null   float64
 45  pixel_5_5  1797 non-null   float64
 46  pixel_5_6  1797 non-null   float64
 47  pixel_5_7  1797 non-null   float64
 48  pixel_6_0  1797 non-null   float64
 49  pixel_6_1  1797 non-null   float64
 50  pixel_6_2  1797 non-null   float64
 51  pixel_6_3  1797 non-null   float64
 52  pixel_6_4  1797 non-null   float64
 53  pixel_6_5  1797 non-null   float64
 54  pixel_6_6  1797 non-null   float64
 55  pixel_6_7  1797 non-null   float64
 56  pixel_7_0  1797 non-null   float64
 57  pixel_7_1  1797 non-null   float64
 58  pixel_7_2  1797 non-null   float64
 59  pixel_7_3  1797 non-null   float64
 60  pixel_7_4  1797 non-null   float64
 61  pixel_7_5  1797 non-null   float64
 62  pixel_7_6  1797 non-null   float64
 63  pixel_7_7  1797 non-null   float64
dtypes: float64(64)
memory usage: 898.6 KB

In [31]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=.25,random_state=42, stratify=y)

In [32]:
min_max_scaler=MinMaxScaler()
X_train_scaled=min_max_scaler.fit_transform(X_train)

In [44]:

X_train_scaled

,0,1,2,3,4,5,6,7,8,9,...,54,55,56,57,58,59,60,61,62,63
0,0.0,0.25,0.7500,1.0000,0.7500,0.0000,0.0000,0.0,0.0,0.466667,...,0.3125,0.000000,0.0,0.000000,0.9375,1.0000,1.0000,0.9375,0.1875,0.0000
1,0.0,0.00,0.0000,0.8125,0.8750,0.0000,0.0000,0.0,0.0,0.000000,...,0.0000,0.000000,0.0,0.000000,0.0625,0.6875,0.5625,0.0000,0.0000,0.0000
2,0.0,0.25,0.6875,1.0000,0.7500,0.0625,0.0000,0.0,0.0,0.600000,...,0.5625,0.000000,0.0,0.222222,0.9375,1.0000,1.0000,0.8125,1.0000,0.0625
3,0.0,0.00,0.6875,0.6250,0.0000,0.0000,0.0000,0.0,0.0,0.000000,...,0.3125,0.076923,0.0,0.000000,0.7500,1.0000,1.0000,1.0000,1.0000,0.7500
4,0.0,0.00,0.1875,0.7500,1.0000,0.6250,0.0000,0.0,0.0,0.133333,...,0.0000,0.000000,0.0,0.000000,0.3125,0.8125,0.0000,0.0000,0.0000,0.0000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1342,0.0,0.00,0.0000,0.3125,0.9375,0.8125,0.0625,0.0,0.0,0.000000,...,0.0625,0.000000,0.0,0.000000,0.0000,0.3750,0.8750,0.7500,0.0625,0.0000
1343,0.0,0.00,0.1250,0.7500,0.4375,0.0000,0.0000,0.0,0.0,0.000000,...,0.1875,0.000000,0.0,0.000000,0.0625,0.8125,0.9375,0.5625,0.0000,0.0000
1344,0.0,0.00,0.0625,0.4375,0.8125,0.6250,0.0000,0.0,0.0,0.133333,...,0.5000,0.000000,0.0,0.000000,0.0000,0.4375,0.9375,1.0000,0.6250,0.0000
1345,0.0,0.00,0.1875,0.8750,0.8125,0.0625,0.0000,0.0,0.0,0.000000,...,0.0000,0.000000,0.0,0.000000,0.3125,0.8125,0.9375,0.4375,0.0000,0.0000
1346,0.0,0.00,0.4375,0.8750,0.6250,0.0000,0.0000,0.0,0.0,0.466667,...,0.8125,0.000000,0.0,0.000000,0.3125,0.8125,1.0000,0.8750,0.3750,0.0000

In [45]:
X_test_scaled=min_max_scaler.fit_transform(X_test)

X_test_scaled

array([[0.    , 0.    , 0.5   , ..., 0.    , 0.    , 0.    ],
       [0.    , 0.    , 0.25  , ..., 0.6875, 0.    , 0.    ],
       [0.    , 0.    , 0.5   , ..., 0.9375, 0.0625, 0.    ],
       ...,
       [0.    , 0.    , 0.4375, ..., 0.375 , 0.    , 0.    ],
       [0.    , 0.    , 0.    , ..., 0.    , 0.    , 0.    ],
       [0.    , 0.    , 0.    , ..., 0.125 , 0.    , 0.    ]],
      shape=(450, 64))

In [47]:
X_train_img=X_train_scaled.reshape(-1,28,28)
X_test_img=X_test_scaled.reshape(-1,28,28)

AttributeError: 'DataFrame' object has no attribute 'reshape'